name: e2e

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

defaults:
  run:
    shell: bash

env:
  # https://github.com/google/go-containerregistry/pull/125 allows insecure registry for
  # '*.local' hostnames. This works both for `ko` and our own tag-to-digest resolution logic,
  # thus allowing us to test without bypassing tag-to-digest resolution.
  CLUSTER_DOMAIN: c${{ github.run_id }}.local
  REGISTRY_NAME: registry.local
  REGISTRY_PORT: 5000
  KO_DOCKER_REPO: registry.local:5000/knative
  KIND_VERSION: 0.19.0
  GOTESTSUM_VERSION: 1.7.0
  KAPP_VERSION: 0.46.0
  YTT_VERSION: 0.40.1
  KO_FLAGS: --platform=linux/amd64
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.21.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.x

    - name: Setup Cache Directories
      run: |
        mkdir -p ~/artifacts/build
        mkdir -p ~/artifacts/registry

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
           ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Install the latest release of ko
    - name: Install ko
      uses: ko-build/setup-ko@v0.6

    - name: Setup Registry
      run: |
        docker run -d --restart=always \
          -p $REGISTRY_PORT:$REGISTRY_PORT \
          -v ~/artifacts/registry:/var/lib/registry \
          --name $REGISTRY_NAME registry:2

        # Make the $REGISTRY_NAME -> 127.0.0.1, to tell `ko` to publish to
        # local reigstry, even when pushing $REGISTRY_NAME:$REGISTRY_PORT/some/image
        sudo echo "127.0.0.1 $REGISTRY_NAME" | sudo tee -a /etc/hosts
